# Generated by Django 5.1.7 on 2025-04-01 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=1024)),
                ('mass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitute', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishInSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_in_sets', to='notmeat_app.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='dish_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_sets', to='notmeat_app.dishcategory')),
                ('dishes', models.ManyToManyField(related_name='dish_sets', through='notmeat_app.DishInSet', to='notmeat_app.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dishinset',
            name='dish_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes_in_set', to='notmeat_app.dishset'),
        ),
        migrations.CreateModel(
            name='DishSetInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dish_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_set_in_orders', to='notmeat_app.dishset')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('PR', 'Payment received'), ('CK', 'Cooking'), ('DL', 'Delivering'), ('FN', 'Finished')], max_length=2)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='notmeat_app.deliveryaddress')),
                ('dish_sets', models.ManyToManyField(related_name='orders', through='notmeat_app.DishSetInOrder', to='notmeat_app.dishset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dishsetinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_sets_in_order', to='notmeat_app.order'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_optional', models.BooleanField()),
                ('amount', models.FloatField()),
                ('reason', models.CharField(max_length=256)),
                ('dish_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='notmeat_app.dishset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='notmeat_app.order')),
            ],
        ),
    ]
